### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by simonsan** [SiegeEngineers/aoc-reference-data#106]
This assumes that our standard workflow is always creating PRs also from bots and lock the `master` (main) branch against modifications.

What we could check for:

- [x] Doublettes being added (check for doubles from fields like `liquipedia`, `Platforms->DE` and `Platforms->Voobly` ids, `name`, `aoeelo`)
  - [x] basically index those fields and throw an error if values already exists in the file
- [x] item IDs not being reused, kept unique (done in #107)
- [x] Probably implicit, but also valid YAML (done in #109)
- [x] Valid `ISO 3166-1 alpha-2` country code
  - [x] https://pypi.org/project/pycountry/
  - [x] https://pypi.org/project/iso3166/
- [ ] other stuff (additions?)

**Comment by happyleavesaoc** [comment]
- Probably implicit, but also valid YAML.
- Valid `ISO 3166-1 alpha-2` country code
