### ISSUE TITLE
CI: Check for `no` that is considered as a boolean by YAML spec

### ISSUE THREAD

**Issue by simonsan** [SiegeEngineers/aoc-reference-data#133]
Regarding: https://github.com/SiegeEngineers/aoc-reference-data/commit/41e8502533f8d20b134101ac4267d698b11a40bc

We should check in our CI for using `no` anywhere as a `boolean` instead of a `string`.

See YAML spec: https://yaml.org/type/bool.html

> y|Y|yes|Yes|YES|n|N|no|No|NO
|true|True|TRUE|false|False|FALSE
|on|On|ON|off|Off|OFF

All of these without quotes are considered booleans. Would probably make sense to try to parse e.g. the countries and other things as boolean and compare to fields that shouldn't contain/be a boolean.

**Comment by happyleavesaoc** [comment]
Stale. Closing.
