### ISSUE TITLE
Add license to the repository

### ISSUE THREAD

**Issue by simonsan** [SiegeEngineers/aoc-reference-data#3]
"When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you."

https://choosealicense.com/no-permission/

Would be nice if there would be a license added to this repository

**Comment by HSZemi** [comment]
In what way is this a "creative work"?

**Comment by simonsan** [comment]
> In what way is this a "creative work"?

That is just a quote from the page where to find the licenses. The point still stands, it is not clear how the data can be used because there is a license missing.

Maybe this fits better then :-) 
https://opendefinition.org/guide/data/

**Comment by happyleavesaoc** [comment]
There is data in this repository that is not mine to license. For example, all the RMS scripts and the dataset information. I don't intend to apply a license to this repository. If you fear legal repercussions, do not use it.
