### ISSUE TITLE
Keep datasets automatically in sync with recent patches

### ISSUE THREAD

**Issue by simonsan** [SiegeEngineers/aoc-reference-data#42]
https://github.com/SiegeEngineers/aoc-reference-data/blob/master/data/datasets/100.json
https://github.com/SiegeEngineers/aoc-reference-data/blob/master/data/datasets/1.json

Could we discuss a way here how we could keep these files automatically in sync with recent patch changes of AoE2DE?
It would be really cool to have easy access to these information to use for streaming overlays for example.

Or is there already a repository for this and I'm overlooking something?

**Comment by happyleavesaoc** [comment]
The AGE lib could do most of the work. That's how I generated the non-DE versions.

**Comment by simonsan** [comment]
> The AGE lib could do most of the work. That's how I generated the non-DE versions. That's also how hszemi's halfon works.

Ah ok, so is there already some code existing to generate the files in datasets? Might you be able to share it or commit it to this repository, so we store it together with the exported files?

I guess in the longer run, when [genie-rs/dat](https://github.com/SiegeEngineers/genie-rs) is supporting 2DE files completely, it might be also easy to include that in that helper utility directly. Until then to get used to the process would be really nice to share that in here.

**Comment by happyleavesaoc** [comment]
Stale. Closing.
