### ISSUE TITLE
Datalist for AoE related pages

### ISSUE THREAD

**Issue by simonsan** [SiegeEngineers/aoc-reference-data#44]
Does it make sense to collect a list of all the different pages one can get information from like aoe2insights, aoe2techtree, aoe2recs, etc. with a `description`-field for the content and a `tag`? Maybe as an overview as in `platforms.json` and easy to parse for future chat commands for example?

Maybe like this(?):
```
name: String
url: String
description: String
tags: [ Array of Strings ]
preview-url: String
contact: String
```

`preview-url` could be a screenshot taken at a certain time, not sure if it's needed. Just an idea.
`contact` could be an eMail-Address or a link to a contact form, discord username (or others and more than one)

**Comment by happyleavesaoc** [comment]
I can't think of a usecase, but if there is one, feel free to add this data!

**Comment by simonsan** [comment]
> I can't think of a usecase, but if there is one, feel free to add this data!

Maybe to generate something like AoEnexus does as a sidebar:

![2020-12-12 20_12_59-Window-Screenshot](https://user-images.githubusercontent.com/14062932/101992892-a2ebaa00-3cb6-11eb-935d-b7279545c4bb.png)

With the tags used as a filter

**Comment by paulirish** [comment]
i do happily turn to aoe2.se every once in a while. (though it also gets out of date and I then browse the SE github org repos).

Perhaps on aoe2.se there could be a "Community projects" section for non-SE stuff that'd be populated by this.

**Comment by simonsan** [comment]
> Perhaps on aoe2.se there could be a "Community projects" section for non-SE stuff that'd be populated by this.

any information you still miss from #46 ?

**Comment by simonsan** [comment]
Probably better to include the list on https://www.aoe2sheet.info/ on top as a small scrollable portal, I feel now.
