### ISSUE TITLE
Some Input for community_pages.yaml

### ISSUE THREAD

**Issue by simonsan** [SiegeEngineers/aoc-reference-data#56]
Temporary collection for future additions:
https://github.com/Arkanosis/awesome-aoe2

I also asked in the following repository if it makes sense to centralize the data list and pull it in from this repository here.
https://github.com/collinstommy/aoe-library/blob/main/AOELibrary.csv

Tracking: https://github.com/collinstommy/aoe-library/issues/2

**Comment by Arkanosis** [comment]
Hi @simonsan, hi @happyleavesaoc,

I initially bootstrapped the awesome-aoe2 list as [I realized I was not the only one who needed something like it](https://www.reddit.com/r/aoe2/comments/kuefff/is_there_a_website_with_a_list_of_all_aoe_related/), but I think your machine-friendly approach is much more valuable in the long run. The fact this resource could be shared with a very nice front-end like AOE Library sounds great to me.

Are you still looking for assistance as mentioned in the README? I'd be glad to help — and probably more motivated to do that within a team than on my own.

A question though… I've made sure for awesome-aoe2 to state that the data was released under the CC-0 to ensure anybody could use it, and @collinstommy released its resource under the MIT license (I assume for the same reasons), but I don't see any license for this repository. May I suggest to add one? I understand this could be difficult for the repository as a whole, but for manually curated resources, maybe? As the number of unique contributors grows, this might become more difficult in the future.

Thanks!

**Comment by simonsan** [comment]
Regarding licensing: there was some discussion about it before: 
https://github.com/SiegeEngineers/aoc-reference-data/issues/3

It would be absolutely awesome, to make this list as complete as possible, for sure. And I think help/contributions are always appreciated. :)

**Comment by happyleavesaoc** [comment]
Willing to entertain a license for community-sourced portions of this repository, if there is a mechanism to do so. Licenses normally apply to the whole repo and I don't want to be misleading or appear to extend it to data in this repo that is not appropriate to license.

**Comment by collinstommy** [comment]
@simonsan 

I created a PR to add the data from `aoe-library` to this repo:
https://github.com/SiegeEngineers/aoc-reference-data/pull/63

Its missing preview images. Do you just grab a screenshot for those?

### A few suggestions for new fields(community_pages)
**title**
I'd like to move aoe-library to use data from this repo. One thing that aoe-library uses that is missing is a `title`. Is this something we could add? I have titles in aoe-library that we can use.

**supported tags**
We could add a list of allowed tags somewhere. Its not immediately obvious what are the various tags. If this was defined in yml it would make contributing easy as well as being useful to build filters off for aoe-library UI

### players.yaml
I see that there is lot of player data. I would love to use this data on aoe-library. We have some twitch/youtube accounts
in the aoe-library list but I would like to use the data set here as its more extensive. At the moment I have twitch and youtube accounts as separate items for a single player, I'm considering updating the UI to have these as a single item. It would be easier to consume the data at `players.yaml` using this method.

**Comment by simonsan** [comment]
> 
> 
> @simonsan
> 
> I created a PR to add the data from `aoe-library` to this repo:
> #63

Great! <3

> Its missing preview images. Do you just grab a screenshot for those?
> ### A few suggestions for new fields(community_pages)
> 
> **title**
> I'd like to move aoe-library to use data from this repo. One thing that aoe-library uses that is missing is a `title`. Is this something we could add? I have titles in aoe-library that we can use.

I think it makes sense yes!

> **supported tags**
> We could add a list of allowed tags somewhere. Its not immediately obvious what are the various tags. If this was defined in yml it would make contributing easy as well as being useful to build filters off for aoe-library UI
> ### players.yaml

Yeah, I thought about this as well when creating it, to have something like `unique ids` for the tags and use them in the `community_pages.yaml`. Why I decided against it back then was the overall usability when adding things, because you would know which IDs are what. Afterwards I thought about it and what would make sense is to create something like having a first object with the tags and then a second object with all the community pages. I wouldn't necessarily create another yml file for that but keep it in that same file imho, so you do not need to make two request to get the tags and the pages, but just one and process each object.

> I see that there is lot of player data. I would love to use this data on aoe-library. We have some twitch/youtube accounts
> in the aoe-library list but I would like to use the data set here as its more extensive. At the moment I have twitch and youtube accounts as separate items for a single player, I'm considering updating the UI to have these as a single item. It would be easier to consume the data at `players.yaml` using this method.

For sure, go on - that's the purpose. :)

**Comment by collinstommy** [comment]
> I wouldn't necessarily create another yml file for that but keep it in that same file imho, so you do not need to make two request to get the tags and the pages, but just one and process each object.

Yep, agree it would be best to keep in a single file. 

We could have a structure like:
```yml
- metadata
  tags: 
    - "Leaderboard"
    - "Lobbies"
- list
  - url: "aoe-elo.com"
    https: true
    description: "Player rating, based only on tournament games"
    tags:
      - "Ratings"
      - "Tournaments"
      - "Statistics"
      - "API"
      - 
```

Metadata could be easily added to in the future

**Comment by simonsan** [comment]
Yes, that would be also how I would imagine it. Probably worth it though, to first merge #63 and then get on that thing later in another PR to have an easier to follow commit history.

**Comment by happyleavesaoc** [comment]
Stale. Closing.
