### ISSUE TITLE
Discussion: Criteria for Player inclusion

### ISSUE THREAD

**Issue by simonsan** [SiegeEngineers/aoc-reference-data#70]
With a growing community and usage of this repository comes also the need for transparency on certain topics, that got handled internally before or were not really worth thinking about: What are our criteria to include players into the `players.yaml` file?

**Comment by happyleavesaoc** [comment]
Great discussion topic. Here's a few automatic approvals I'd propose at minimum:

1. player is on Liquipedia
2. player is on aoe-elo

Also want to capture key community figures who aren't necessarily pros, and certain bad actors. These are harder to quantify.

**Comment by simonsan** [comment]
For the first section to add maybe (?):

3. player is regularly streaming AoE on Twitch (affiliated/partnered)
4.  player has rating >2X00?

**Comment by happyleavesaoc** [comment]
Twitch Partner is a good one. What about top 200 or 300 RM 1v1 instead - that way rating inflation doesn't impact criteria.

**Comment by simonsan** [comment]
@polskafan Any ideas to add?

**Comment by happyleavesaoc** [comment]
https://github.com/SiegeEngineers/aoc-reference-data/commit/39c6825f1d682055c7936007b7e5f12e1d7bff40
