### ISSUE TITLE
Misleading Ranking for players in the Leaderboard

### ISSUE THREAD

**Issue by umutbalkan** [SiegeEngineers/aoc-reference-data#89]
I'm talking about Ertug. His account is clearly rank4 in EW ladder, but according to some `rationale` you decided it's best to not to display  **correctly** in your service. Anyways it says Mr.Yo is rank4 there. 

I don't know what is your reasoning behind this but this is clearly "misleading" and therefore it is immoral.

You may still don't want to put Ertug in the ladder but by doing so you are **delibaretly misleading** people, this is no joke. You can correct your mistake by allocating people to correct spots. (i. e. Mr. Yo to rank5 and so on).

<img width="326" alt="Screen Shot 2021-07-13 at 12 03 13" src="https://user-images.githubusercontent.com/8284138/125423981-b64b378b-4463-42ec-a535-5f2b15a98d13.png">
<img width="503" alt="Screen Shot 2021-07-13 at 12 02 43" src="https://user-images.githubusercontent.com/8284138/125424005-40a108a5-a84e-41db-bd3b-a0c909b8d7a6.png">

**Comment by umutbalkan** [comment]
You could have display the ladder like this, instead. So people have a chance know your "decisions" and attitudes towards certain things. 
<img width="849" alt="Screen Shot 2021-07-13 at 12 44 35" src="https://user-images.githubusercontent.com/8284138/125430642-88053d6c-6502-49b4-9e0d-424515ba863a.png">

**Comment by happyleavesaoc** [comment]
@umutbalkan Hello, this is the wrong place for this commentary. We do not maintain `aoe2.net`. This repository only contains the data correlating between profile IDs and players.

**Comment by simonsan** [comment]
@Aoe2NET might chime in here
